version: '3.9'

services:
  db:
    image: postgres:13
    container_name: drink-db
    ports:
      - ${DB_PORT}:5432
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_DB=${DB_NAME}
    restart: always

volumes:
  db:
    driver: local
